contact_links:
  - name: Discussion
    about: Discuss your problem here
    url: https://github.com/Ajayos/keerthana/discussions/new
  - name: Discord
    about: Join our discord to discuss together
    url: https://discord.gg/xecWC6H2
