name: Publish to GitHub Packages

on:
  push:
    branches:
      - dist

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: publish to npm
        run: |
          git config --global user.name "Ajay o s"
          git config --global user.email "ajayosakhub@gmail.com"
          npm publish --access public registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TOKEN  }}