name: PR Comment

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - unlocked

jobs:
  pr-comment:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.TOKEN}}
          message-id: pr-test
          message: |
            Thanks for your contribution.

            The next step is to wait for review and approval to merge it to main repository

            The community can help reacting with a thumb up (:thumbsup:) for approval and rocket (:rocket:) for who has tested it.

            To test this PR you can run the following command below:
            ```
            # NPM
            npm install @ajayos/keerthana@${{ github.event.pull_request.head.repo.full_name }}#${{ github.event.pull_request.head.ref }}
            # YARN v2
            yarn add @ajayos/keerthana@${{ github.event.pull_request.head.repo.full_name }}#${{ github.event.pull_request.head.ref }}
            ```
